### ISSUE TITLE
MediaMTX server crashed with WebRTC playback

### ISSUE THREAD

**Issue by MengLi619** [bluenviron/mediamtx#3813]
### Which version are you using?

1.9.1

### Which operating system are you using?

Linux amd64 Docker

### Describe how to replicate the issue

1. start the server
2. publish with RTSP (Pull Camera Source)
3. read with WHEP

The server crashed after writing many `write queue is full`.
```
2024-09-27T09:01:30.337201952Z 2024/09/27 09:01:30 WAR [WebRTC] [session 3167309c] write queue is full
2024-09-27T09:01:30.337218312Z 2024/09/27 09:01:30 WAR [WebRTC] [session 8568a6a8] write queue is full
2024-09-27T09:01:30.337225712Z 2024/09/27 09:01:30 WAR [WebRTC] [session 9e474a48] write queue is full
2024-09-27T09:01:30.337232152Z 2024/09/27 09:01:30 WAR [WebRTC] [session b7f8b418] write queue is full
2024-09-27T09:01:30.337238242Z 2024/09/27 09:01:30 WAR [WebRTC] [session 014f3704] write queue is full
2024-09-27T09:01:30.337243772Z 2024/09/27 09:01:30 WAR [WebRTC] [session df1aa042] write queue is full
2024-09-27T09:01:30.337249432Z 2024/09/27 09:01:30 WAR [WebRTC] [session 25845cd2] write queue is full
2024-09-27T09:01:30.348285856Z 2024/09/27 09:01:30 WAR [WebRTC] [session 6950b7d0] write queue is full
2024-09-27T09:01:30.348301756Z 2024/09/27 09:01:30 WAR [WebRTC] [session 6aa7adb5] write queue is full
2024-09-27T09:01:30.348306696Z 2024/09/27 09:01:30 WAR [WebRTC] [session 49a4aec3] write queue is full
2024-09-27T09:01:30.348310586Z 2024/09/27 09:01:30 WAR [WebRTC] [session 890bd1dd] write queue is full
2024-09-27T09:01:30.358718204Z 2024/09/27 09:01:30 WAR [WebRTC] [session e64ad341] write queue is full
2024-09-27T09:01:30.360542722Z 2024/09/27 09:01:30 WAR [WebRTC] [session 7ffd14c3] write queue is full
2024-09-27T09:01:30.366997752Z 2024/09/27 09:01:30 WAR [WebRTC] [session 7dbb815d] write queue is full
2024-09-27T09:01:30.367013152Z 2024/09/27 09:01:30 WAR [WebRTC] [session d1a6aa3f] write queue is full
2024-09-27T09:01:30.367019523Z 2024/09/27 09:01:30 WAR [WebRTC] [session e661f0fd] write queue is full
2024-09-27T09:01:30.367028023Z 2024/09/27 09:01:30 WAR [WebRTC] [session e18a4439] write queue is full
2024-09-27T09:01:30.367036253Z 2024/09/27 09:01:30 WAR [WebRTC] [session 0d9d7cab] write queue is full
2024-09-27T09:01:30.367041533Z 2024/09/27 09:01:30 WAR [WebRTC] [session 286a4e77] write queue is full
2024-09-27T09:01:30.367046233Z 2024/09/27 09:01:30 WAR [WebRTC] [session ad6160fc] write queue is full
2024-09-27T09:01:30.367051333Z 2024/09/27 09:01:30 WAR [WebRTC] [session 4e9c284d] write queue is full
2024-09-27T09:01:30.379909444Z 2024/09/27 09:01:30 INF [WebRTC] [session 1fb05bb1] peer connection established, local candidate: host/udp/172.17.0.1/8189, remot
e candidate: prflx/udp/218.255.120.74/35762
2024-09-27T09:01:30.383507758Z panic: close of closed channel
2024-09-27T09:01:30.383551298Z
2024-09-27T09:01:30.383681099Z goroutine 19287324 [running]:
2024-09-27T09:01:30.383792781Z github.com/bluenviron/mediamtx/internal/protocols/webrtc.(*PeerConnection).Start.func3(0x3)
2024-09-27T09:01:30.383815161Z  /root/mediamtx/internal/protocols/webrtc/peer_connection.go:274 +0x259
2024-09-27T09:01:30.383824621Z created by github.com/pion/webrtc/v3.(*PeerConnection).onConnectionStateChange in goroutine 19287323
2024-09-27T09:01:30.383830841Z  /root/go/pkg/mod/github.com/aler9/webrtc/v3@v3.0.0-20240610104456-eaec24056d06/peerconnection.go:500 +0x16f
```

**Comment by aler9** [comment]
Thanks for reporting the crash, this is fixed by #3815.

I can't see any relationship with #2320.
