### ISSUE TITLE
rtsp and vp8: segmentation violation code=0x1 addr=0x30 pc=0x6a4af0]

### ISSUE THREAD

**Issue by terion-name** [bluenviron/mediamtx#3978]
### Which version are you using?

1.9.3

### Which operating system are you using?

Linux amd64 Docker, Linux arm64 Docker

### Describe how to replicate the issue

1. start the server (docker, docker compose, mac m1, but `platform: linux/amd64` doesn't help)
2. publish with `ffmpeg -stream_loop -1 -re -i ~/Downloads/Big_Buck_Bunny_720_10s_30MB.webm -c copy -rtsp_transport tcp -f rtsp "rtsp://localhost:8554/test~1~2~3"`

### Server logs

```
2024/11/25 16:08:57 INF [RTSP] [conn 192.168.107.1:39106] opened
2024-11-25T16:08:57.417346875Z 2024/11/25 16:08:57 INF [RTSP] [conn 192.168.107.1:39106] runOnConnect command started
2024-11-25T16:08:57.430457790Z 2024/11/25 16:08:57 INF [RTSP] [session 9c53ff00] created by 192.168.107.1:39106
2024-11-25T16:08:57.435680206Z 2024/11/25 16:08:57 WAR [path test~1~2~3] [recorder] no supported tracks found, skipping recording
2024-11-25T16:08:57.436391248Z   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2024-11-25T16:08:57.436432998Z                                  Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
panic: runtime error: invalid memory address or nil pointer dereference
2024-11-25T16:08:57.438546122Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6a4af0]
2024-11-25T16:08:57.438548081Z 
2024-11-25T16:08:57.438549497Z goroutine 63 [running]:
2024-11-25T16:08:57.438550997Z github.com/bluenviron/mediamtx/internal/stream.(*streamReader).start(0x0)
2024-11-25T16:08:57.438552289Z 	/s/internal/stream/stream_reader.go:30 +0x20
2024-11-25T16:08:57.438553831Z github.com/bluenviron/mediamtx/internal/stream.(*Stream).StartReader(0x4000114ae0, {0x166b040, 0x40006fc0c0})
2024-11-25T16:08:57.438555164Z 	/s/internal/stream/stream.go:179 +0x98
2024-11-25T16:08:57.438556289Z github.com/bluenviron/mediamtx/internal/recorder.(*recorderInstance).initialize(0x40006fc0c0)
2024-11-25T16:08:57.438557622Z 	/s/internal/recorder/recoder_instance.go:60 +0x244
2024-11-25T16:08:57.438558747Z github.com/bluenviron/mediamtx/internal/recorder.(*Recorder).Initialize(0x40000fe280)
2024-11-25T16:08:57.438559914Z 	/s/internal/recorder/recorder.go:58 +0x144
2024-11-25T16:08:57.438591914Z github.com/bluenviron/mediamtx/internal/core.(*path).startRecording(0x4000494a00)
2024-11-25T16:08:57.438594497Z 	/s/internal/core/path.go:818 +0x194
2024-11-25T16:08:57.438595622Z github.com/bluenviron/mediamtx/internal/core.(*path).setReady(0x4000494a00, 0x4000043c70, 0x0)
2024-11-25T16:08:57.438596997Z 	/s/internal/core/path.go:725 +0xfc
2024-11-25T16:08:57.438598122Z github.com/bluenviron/mediamtx/internal/core.(*path).doStartPublisher(0x4000494a00, {{0x16711d8, 0x4000312000}, 0x4000043c70, 0x0, 0x4000090360})
2024-11-25T16:08:57.438610456Z 	/s/internal/core/path.go:498 +0xd4
2024-11-25T16:08:57.438612331Z github.com/bluenviron/mediamtx/internal/core.(*path).runInner(0x4000494a00)
2024-11-25T16:08:57.438613581Z 	/s/internal/core/path.go:295 +0x5b0
2024-11-25T16:08:57.438614747Z github.com/bluenviron/mediamtx/internal/core.(*path).run(0x4000494a00)
2024-11-25T16:08:57.438615956Z 	/s/internal/core/path.go:194 +0x2d4
2024-11-25T16:08:57.438617039Z created by github.com/bluenviron/mediamtx/internal/core.(*path).initialize in goroutine 16
2024-11-25T16:08:57.438618331Z 	/s/internal/core/path.go:144 +0x55c

```

### Network dump

not relevant

**Comment by aler9** [comment]
Thanks for reporting the crash, this is fixed by #3996
